# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.
# @param {String} s
# @param {String} t
# @return {Character}
def find_the_difference(s, t)
    s << t
    res = 0
    idx = 0
    while idx < s.length
        res = res ^ s[idx].ord
        idx += 1
    end
    res.chr
end
