SELECT COUNT(*) FROM CITY WHERE POPULATION > 100000

SELECT SUM(POPULATION) FROM CITY WHERE DISTRICT = 'California'

SELECT AVG(POPULATION) FROM CITY WHERE DISTRICT = 'CALIFORNIA'

SELECT FLOOR(AVG(POPULATION)) FROM CITY

SELECT SUM(POPULATION) FROM CITY WHERE COUNTRYCODE = 'JPN'

SELECT
(SELECT POPULATION FROM CITY ORDER BY POPULATION DESC LIMIT 1)
-
(SELECT POPULATION FROM CITY ORDER BY POPULATION ASC LIMIT 1)
